<?php

namespace App\Http\Requests\Api;

use Illuminate\Foundation\Http\FormRequest;

class TopicRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        switch ($this->method()){
            case 'POST':
                return [
                    'title'=>'required|string|min:2',
                    'body'=>'required|string|min:3',
                    //numeric 验证字段必须为数值。
                    'category_id' =>'required|numeric|exists:categories,id',
                ];
                break;
            case 'PATCH':
                return [
                    'title'=>'string|min:2',
                    'body'=>'string|min:3',
                    //exists:table,column；验证的字段必须存在于给定的数据库表中。
                    'category_id'=>'numeric|exists:categories,id',
                ];
                break;
            default:
            {
                return [];
            }
        }
    }

    public function attributes()
    {
        return [
            'title'=>'标题',
            'body'=>'内容',
            'category_id'=>'分类',
        ]; // TODO: Change the autogenerated stub
    }
    public function messages()
    {
        return [
            'title.min'=>'标题最少两个字符',
            'body.min'=>'文章内容必须至少三个字符',
        ]; // TODO: Change the autogenerated stub
    }
}
